# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Example Project' do
	pod 'RTFAddLocationViewController’, :head
end

target 'Example ProjectTests' do

end

